---
openapi: 3.0.1
info:
  title: Good Night Sleep Tracking API
  version: v1
  description: API for tracking sleep patterns with follow/unfollow functionality.
paths:
  "/api/users/{other_user_id}/follow":
    post:
      summary: Follow a user
      tags:
      - Followerships
      description: Follow another user.
      security:
      - UserAuth: []
      parameters:
      - name: other_user_id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '201':
          description: Successfully followed user
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/FollowershipResponse"
        '404':
          description: User not found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorResponse"
        '422':
          description: Cannot follow self
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorResponse"
  "/api/users/{other_user_id}/unfollow":
    delete:
      summary: Unfollow a user
      tags:
      - Followerships
      description: Unfollow another user.
      security:
      - UserAuth: []
      parameters:
      - name: other_user_id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Successfully unfollowed user
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/FollowershipResponse"
        '404':
          description: User not found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorResponse"
        '422':
          description: Not following user
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorResponse"
  "/api/sleep_records":
    post:
      summary: Clock in or out
      tags:
      - Sleep Records
      description: Clock in or out for sleep tracking.
      security:
      - UserAuth: []
      parameters: []
      responses:
        '201':
          description: Successfully clocked in
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/SleepRecordResponse"
        '200':
          description: Successfully clocked out
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/SleepRecordResponse"
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorResponse"
        '422':
          description: No active sleep record
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorResponse"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                action_type:
                  type: string
                  enum:
                  - clock_in
                  - clock_out
              required:
              - action_type
  "/api/sleep_records/feeds":
    get:
      summary: Get sleep record feeds
      tags:
      - Sleep Records
      description: Get sleep record feeds from followed users (previous week).
      security:
      - UserAuth: []
      parameters:
      - name: page
        in: query
        required: false
        description: Page number for pagination (default 1)
        schema:
          type: integer
      - name: per_page
        in: query
        required: false
        description: Number of records per page (default 20)
        schema:
          type: integer
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/SleepRecordFeedResponse"
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorResponse"
  "/api/sleep_records/clock_in_history":
    get:
      summary: Get clock in history
      tags:
      - Sleep Records
      description: |-
        Retrieve a paginated list of clock in timestamps for the authenticated user.
        Records are ordered by creation date (newest first).
      security:
      - UserAuth: []
      parameters:
      - name: page
        in: query
        required: false
        description: Page number for pagination (default 1)
        schema:
          type: integer
      - name: per_page
        in: query
        required: false
        description: Number of records per page (default 20)
        schema:
          type: integer
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ClockInHistoryResponse"
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorResponse"
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000
components:
  securitySchemes:
    UserAuth:
      type: apiKey
      in: header
      name: Authorization
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: An error message
        code:
          type: string
          example: ERROR_CODE
      required:
      - error
      - code
    User:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: John Doe
      required:
      - id
      - name
    SleepRecord:
      type: object
      properties:
        user:
          "$ref": "#/components/schemas/User"
        clock_in_at:
          type: string
          format: date-time
          example: '2025-01-15T22:00:00Z'
        clock_out_at:
          type: string
          format: date-time
          nullable: true
          example: '2025-01-16T06:00:00Z'
        duration:
          type: integer
          nullable: true
          example: 28800
        created_at:
          type: string
          format: date-time
          example: '2025-01-15T22:00:00Z'
      required:
      - user
      - clock_in_at
      - created_at
    SleepRecordResponse:
      type: object
      properties:
        action:
          type: string
          enum:
          - clock_in
          - clock_out
        data:
          "$ref": "#/components/schemas/SleepRecord"
        message:
          type: string
        code:
          type: string
          example: SUCCESS
      required:
      - action
      - data
      - message
      - code
    SleepRecordFeedResponse:
      type: object
      properties:
        data:
          type: array
          items:
            "$ref": "#/components/schemas/SleepRecord"
        total:
          type: integer
        page:
          type: integer
        per_page:
          type: integer
      required:
      - data
      - total
      - page
      - per_page
    ClockInHistoryResponse:
      type: object
      properties:
        data:
          type: array
          items:
            type: string
            format: date-time
        total:
          type: integer
        page:
          type: integer
        per_page:
          type: integer
      required:
      - data
      - total
      - page
      - per_page
    Followership:
      type: object
      properties:
        id:
          type: integer
          example: 1
        follower_id:
          type: integer
          example: 123
        followed_id:
          type: integer
          example: 456
        status:
          type: string
          enum:
          - active
          - unfollowed
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
      - id
      - follower_id
      - followed_id
      - status
      - created_at
      - updated_at
    FollowershipResponse:
      type: object
      properties:
        action:
          type: string
          enum:
          - follow
          - unfollow
        message:
          type: string
        code:
          type: string
          example: SUCCESS
      required:
      - action
      - message
      - code
